
////

Used in:


////

== Overview
_include/todo/Management.command_center.add_existing_server_to_company.adoc
_include/todo/Management.command_center.allow_new_wvd_connections.adoc
_include/todo/Management.command_center.backup_list.adoc
_include/todo/Management.command_center.backup_restore_to_drive.adoc
_include/todo/Management.command_center.backup_server_now.adoc
_include/todo/Management.command_center.backups_run_all_scheduled.adoc
_include/todo/Management.command_center.change_data_home_pro_folders.adoc
_include/todo/Management.command_center.change_password.adoc
_include/todo/Management.command_center.copy_template_to_gallery.adoc
_include/todo/Management.command_center.create_azure_file_share.adoc
_include/todo/Management.command_center.create_azure_netapp_files_share.adoc
_include/todo/Management.command_center.create_cache_company.adoc
_include/todo/Management.command_center.create_data_center_site.adoc
_include/todo/Management.command_center.create_no_server_company.adoc
_include/todo/Management.command_center.create_server_from_backup.adoc
_include/todo/Management.command_center.create_server_from_clone.adoc
_include/todo/Management.command_center.create_server_from_template.adoc
_include/todo/Management.command_center.create_template_phase_1.adoc
_include/todo/Management.command_center.create_template_phase_3.adoc
_include/todo/Management.command_center.created_company.adoc
_include/todo/Management.command_center.delete_backup.adoc
_include/todo/Management.command_center.delete_datacenter_site.adoc
_include/todo/Management.command_center.delete_drives_form_server.adoc
_include/todo/Management.command_center.delete_server.adoc
_include/todo/Management.command_center.delete_template.adoc
_include/todo/Management.command_center.edit_provisioning_collection.adoc
_include/todo/Management.command_center.edit_resource_pool.adoc
_include/todo/Management.command_center.edit_workload_schedule.adoc
_include/todo/Management.command_center.exclude_server_from_monitoring.adoc
_include/todo/Management.command_center.expand_drive.adoc
_include/todo/Management.command_center.file_migration.adoc
_include/todo/Management.command_center.generate_email_reports.adoc
_include/todo/Management.command_center.generate_reports.adoc
_include/todo/Management.command_center.install_notepad++_Chrome.adoc
_include/todo/Management.command_center.install_thinprint_license_server.adoc
_include/todo/Management.command_center.list_drives_for_server.adoc
_include/todo/Management.command_center.list_long_running_operations.adoc
_include/todo/Management.command_center.load_active_users.adoc
_include/todo/Management.command_center.load_cache_companies.adoc
_include/todo/Management.command_center.load_hypervisor_config_options.adoc
_include/todo/Management.command_center.load_hypervisor_type.adoc
_include/todo/Management.command_center.load_machine_series.adoc
_include/todo/Management.command_center.load_machine_sizes.adoc
_include/todo/Management.command_center.load_max_concurrent_users.adoc
_include/todo/Management.command_center.load_resource_pool_data.adoc
_include/todo/Management.command_center.load_server_resource_report_data.adoc
_include/todo/Management.command_center.load_servers_for_company.adoc
_include/todo/Management.command_center.load_storage_types.adoc
_include/todo/Management.command_center.load_templates.adoc
_include/todo/Management.command_center.load_virtual_machines.adoc
_include/todo/Management.command_center.make_server_active.adoc
_include/todo/Management.command_center.make_server_data_server.adoc
_include/todo/Management.command_center.migrate_company.adoc
_include/todo/Management.command_center.move_servers_to_company.adoc
_include/todo/Management.command_center.reboot_server.adoc
_include/todo/Management.command_center.reload_configuration.adoc
_include/todo/Management.command_center.reload_monitored_applications.adoc
_include/todo/Management.command_center.remove_vds_software.adoc
_include/todo/Management.command_center.rename_server.adoc
_include/todo/Management.command_center.resource_allocation_enable.adoc
_include/todo/Management.command_center.run_daily_actions.adoc
_include/todo/Management.command_center.run_daily_maintenance.adoc
_include/todo/Management.command_center.run_program.adoc
_include/todo/Management.command_center.run_resource_allocation.adoc
_include/todo/Management.command_center.run_workload_schedule.adoc
_include/todo/Management.command_center.set_external_dns.adoc
_include/todo/Management.command_center.set_gateway_address.adoc
_include/todo/Management.command_center.set_time_zone.adoc
_include/todo/Management.command_center.should_pool_be_running.adoc
_include/todo/Management.command_center.start_company.adoc
_include/todo/Management.command_center.start_server_for_wake_on_demand.adoc
_include/todo/Management.command_center.start_server.adoc
_include/todo/Management.command_center.stop_company.adoc
_include/todo/Management.command_center.stop_cwagent.adoc
_include/todo/Management.command_center.stop_sddc.adoc
_include/todo/Management.command_center.stop_server.adoc
_include/todo/Management.command_center.test_hypervisor_connection.adoc
_include/todo/Management.command_center.update_active_user_count.adoc
_include/todo/Management.command_center.update_cw_vm_automation_service.adoc
_include/todo/Management.command_center.wildcard_cert_create_new.adoc
_include/todo/Management.command_center.wildcard_cert_install.adoc
