---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Virtual Desktop Service.
keywords:
---

= Virtual Desktop Service Documentation

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: Windows Virtual Desktop

[.lead]
== Overview
NetApp's Virtual Desktop Service (VDS) solves the complexity of deploying and managing virtual desktops in the public cloud, delivered both as a flexible software service to manage your Virtual Desktop Infrastructure (VDI), or as a fully managed VDI as a Service platform. The Virtual Desktop Service removes the complexity of deploying desktops in the cloud taking the hundreds of tasks that took 2-3 days to deploy into just a few hours.

//VIDEO HERE- TBD

=== Virtual Desktop Service Benefits:

* *Reduce Infrastructure Costs*
+
Our customizable resource scheduling system optimizes infrastructure spend up to 50%.

* *Reduce Risk*
+
Deploy desktops into logical workflows per cloud best practices; Such as Microsoft best practice WVD standards.

* *Full Automation*
+
Event driven automation and orchestration engine leveraging your current scripts, making management so easy, general IT administrators can manage your cloud desktops!

* *Turn-Key*
+
Deploy as a do-it-yourself software management service for your choice of VDI environments or choose a fully managed WVD platform service.

* *Multi-Cloud*
+
Control multiple tenants across AWS, Azure and Google with a single graphical user interface.

* *Flexible Control*
+
Maximize business flexibility with a single portal to control every layer of your technology stack.


Learn More: https://cloud.netapp.com/virtual-desktop-service

== Getting Support

Email Support: cjsupport@netapp.com

Phone Support: 844.645.6789 Ext. 2

link:https://cloudjumper.zendesk.com[VDS Support Portal]

Normal Support Business Hours: Monday-Friday, 7:00am-7:00pm Central Time.

* After Hours (On-Call) Support available via Phone only.


== Additional Resources

=== Remote Desktop Services (RDS) Clients
* link:https://cwc.cloudworkspace.com/download/cwc-win-setup.exe[VDS RDS Client for Windows]

* link:https://login.cloudworkspace.com/[VDS Web Client]

* link:https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients[Microsoft RD Client]

=== Windows Virtual Desktop (WVD) Clients
* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-windows-7-10[Microsoft WVD for Windows Client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-web[Microsoft WVD Web Client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-android[Microsoft WVD for Android Client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-macos[Microsoft WVD for macOS Client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-ios[Microsoft WVD for iOS Client]


=== Other Downloads
* link:https://cloudjumper.com/wp-content/uploads/2019/12/RemoteScanEnterpriseUser.zip[RemoteScan Client]

* link:https://cloudjumper.com/cloudworkspaceclient/designer/Cloud%20Workspace%20Designer.exe[Cloud Workspace Client Designer]
