---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Virtual Desktop Service.
keywords:
---

= Virtual Desktop Service documentation

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords:

[.lead]
== Overview
NetApp's Virtual Desktop Service (VDS) solves the complexity of deploying and managing virtual desktops in the public cloud, delivered both as a flexible software service to manage your Virtual Desktop Infrastructure (VDI), or as a fully managed VDI as a Service platform. The Virtual Desktop Service removes the complexity of deploying desktops in the cloud taking the hundreds of tasks that took 2-3 days to deploy into just a few hours.

//VIDEO HERE- TBD

=== Virtual Desktop Service benefits:

* *Reduce infrastructure costs*
+
Our customizable resource scheduling system optimizes infrastructure spend up to 50%.

* *Reduce risk*
+
Deploy desktops into logical workflows per cloud best practices; Such as Microsoft best practice WVD standards.

* *Custom automation*
+
Event driven automation and orchestration engine leveraging your current scripts, making management so easy, general IT administrators can manage your cloud desktops!

* *Turnkey*
+
Deploy as a do-it-yourself software management service for your choice of VDI environments or choose a fully managed WVD platform service.

* *Multi-cloud*
+
Control multiple tenants across AWS, Azure and Google with a single graphical user interface.

* *Flexible control*
+
Maximize business flexibility with a single portal to control every layer of your technology stack.


Learn more: https://cloud.netapp.com/virtual-desktop-service

== Getting support

Email support: VDSsupport@netapp.com

Phone support: 844.645.6789 Ext. 2

link:https://cloudjumper.zendesk.com[VDS support portal]

Normal support business hours: Monday-Friday, 7:00am-7:00pm Central Time.

* After hours (on-call) support available via phone only.


== Additional resources

=== Cost calculator
==== Azure
* link:https://v6.manage.cloudworkspace.com/cost-estimator[]

=== Remote Desktop Services (RDS) clients
* link:https://cwc.cloudworkspace.com/download/cwc-win-setup.exe[VDS RDS client for Windows]

* link:https://login.cloudworkspace.com/[VDS web client]

* link:https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients[Microsoft RD client]

=== Windows Virtual Desktop (WVD) clients
* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-windows-7-10[Microsoft WVD for Windows client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-web[Microsoft WVD web client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-android[Microsoft WVD for Android client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-macos[Microsoft WVD for macOS client]

* link:https://docs.microsoft.com/en-us/azure/virtual-desktop/connect-ios[Microsoft WVD for iOS client]


=== Other downloads
* link:https://cloudjumper.com/wp-content/uploads/2019/12/RemoteScanEnterpriseUser.zip[RemoteScan client]

* link:https://cloudjumper.com/cloudworkspaceclient/designer/Cloud%20Workspace%20Designer.exe[VDS RDS Windows client designer]
