---
sidebar: sidebar
permalink: release_notes_50.html
summary: NetApp VDS Release Notes v5.0
keywords:
---
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: Windows Virtual Desktop

[.lead]
= CWS – v5.0 Release Notes

CloudJumper has released Cloud Workspace Suite 5.0 for general implementation starting in Q4 2016.  This release includes an update of both the CWS APIs and the Admin Control interface.  The release is a significant change and is not “backward compatible” to version 4.x entities.

Version 4.x will continue to be supported until all partner Software Defined Data Centers (SDDCs) have been upgraded to the 5.0 platform, upgrades will be completed by CloudJumper in coordination with each Partner and will not interrupt existing services. There is no upgrade fee or implementation cost to transition. CWS 5 continues to support all of the previous versions’ functionality, and extends new features that enhance both Administrator and End-User experience, and further improve the award winning automation and orchestration introduced with previous releases of Cloud Workspace Suite.

Existing Partners should have little trouble adopting the new Admin interface, and “time to mastery” for new Partners will be even easier.  With CWS 5.0, CloudJumper has re-written all of the platforms APIs into REST API format and completely retired the earlier SOAP APIs.  This updated architecture will make further enhancement by CloudJumper easier and faster, and creates an even friendlier environment for external developers to extend their services and products based on Cloud Workspace.

== Highlights

* Complete UI/UX Rewrite
* Azure AD Integration
* Azure SDDC Self Service Deploy
* App Services
* Resource Scheduling
* Live Server Scaling – Cross Platform
* Automated Server Cloning – Cross Platform
* Customize Drive Shares on a per client basis

== Key Features

=== Azure Active Directory (AD) Integration

* Build SDDC as Private Cloud Active Directory or use Microsoft Azure-AD-as-a-Service
* Combine CWS with Office365
* Support Azure-based SSO & MFA

=== Azure SDDC Self Service Deploy

* Complete integration with Azure
* Rapidly deploy new SDDCs
* Deploy private enterprise Clouds within Azure for any workload including Cloud Workspace managed:  WaaS, App Services, Private Web App & SharePoint

=== App Services

* Deploy application silos for publishing applications as isolated service building blocks
* Apps delivered from ‘public’ app servers to many custom entities
* Apps installed in single app dedicated server pools
* Apps decoupled from user profile and data layer requirements
* Build hyper-scalable app services
* Multiple app services can be combined into user collections
* CWS license tracking and usage reporting

=== Live Server Scaling – Cross Platform

* Intelligent automated scaling of server resources/active servers
* Tightly manage server resources with dynamic increase/decrease while user load changes
* Automatically scale server resources up & down as workload varies

=== Automated Server Cloning – Cross Platform

* Automatically increase server until count availability as defined user count grows
* Adds additional servers to the available resource pools
* Combine with CWS Live Server Scaling capability to create fully automated solution

=== Resource Scheduling

* Schedule service times on a per-customer basis
* Cost containment for Public Cloud
* Shut systems down when not in use and re-activate on pre-defined schedule
