---
sidebar: sidebar
permalink: release_notes_52.html
summary: NetApp VDS Release Notes v5.2
keywords:
---
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: Windows Virtual Desktop

[.lead]

= Cloud Workspace Management Suite – version 5.2

== CWMS 5.2 Release: Mon., December 2, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Monday December 2, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release cycle.

== CWMS 5.2 Release: Thurs., November 14, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday November 14, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release cycle.

== CWMS 5.2 Release: Thurs., October 31, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday October 31, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release cycle.

== CWMS 5.2 Release: Thurs., October 17, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday October 17, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release cycle.

== CWMS 5.2 Release: Thurs., October 3, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday October 3, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release cycle.

== CWMS 5.2 Release: Thurs., September 19, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday September 19, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== Cloud Workspace Management Suite

Default an Azure deployment’s Resource Allocation Type to Fixed; with the VM series/size selected being the VM defined by the Administrator in CWMS
Add search functionality for User Activity audit functionality
Bug fix for incorrectly displaying session inactivity timeout warning after 5 minutes instead of 55 minutes
User Support role fix – a subset of Admins with this role were unable to see the list of Users for their organization
User sorting fix – sorting by username works as intended instead of sorting by status
Ensure Master Client Report is present; hide the non-applicable SPLA report for non-Master Software Partners

=== Cloud Workspace Tools and Services

Enhanced password encryption behind the scenes
Bug fix for Password Enforcement Notification (PEN) where using the “change password at next logon” feature wasn’t working as intended if password expiration dates were set to null by an administrator in CWMGR1

=== Cloud Workspace for Azure Setup App

Fix for international administrators – this on longer requires a State if the Country is not the United States.
Apply CloudJumper via Partner Admin Link (PAL) to present and future Azure deployments at the subscription level

== CWMS 5.2 Release: Thurs., September 5, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday September 5, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== Cloud Workspace Management Suite

Updates to the User Support Only role:
* Add searching for/filtering Users functionality
* Include Connection Status column for Users and their connections
* Provide access to the Force Password Change at Next Login feature
* Remove visibility of the Delete Client function
Enforce logout of CWMS after 1 hour of inactivity
Fix for a display issue where VM series/sizes were displaying incorrectly when viewing VM roles whose Resource Allocation Type is set to Fixed
Fix for a display issue where environments with Workload Scheduling set to Always Off were displaying improper settings in CWMS, despite being correctly set to Always Off behind the scenes
Permissions update – remove Resource Scheduling tab if the CWMS admin does not have access to the Resources function in CWMS

=== Cloud Resource App

Updated functionality – support for Command Line usage

=== Cloud Workspace Tools and Services

Support for the vCloud Rest interface

== CWMS 5.2 Release: Thurs., August 22, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday August 22, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== Cloud Workspace Management Suite

Fix a display issue in the User profile for some monitor sizes
Add clarifying message for non-dynamic App Services notifying admins that it may take a few minutes for changes to take effect
Add resfresh button for non-dynamic App Services to make it easier to tell if new clients/users have been added

=== Cloud Workspace for Azure Setup

Add support for MFA for the registration process when linking to an existing CWMS account
Improvement to post-provisioning instructions – link to new and improved Public KB
Improvement to post-provisioning instructions – link opens in a new tab

=== Cloud Workspace Tools and Services

Bug fix for SSL certificate management on Legacy (2008 R2) environments
Additional health checks for certificate enforcement and lifecycle management

== CWMS 5.2 Release: Thurs., August 8, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday August 8, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

No updates this release.

== CWMS 5.2 Release: Thurs., July 25, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday July 25, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 CWA Setup

Display a message post-provisioning that directs CWA Setup users to the CloudJumper Public KB where they can review next steps and how to refine their deployment
Improved handling of countries outside the United States during the registration process
Added a field to confirm the password of the newly created CWMS login during the CWA Setup process
Remove SPLA licensing section under circumstances where RDS licenses will not be required

=== 5.2 Cloud Workspace Management Suite

Improved HTML5 connection handling for CWMS Admins in single server deployments
Bug fix for a scenario where restarting a user’s processing (when it had failed previously) resulted in an “Internal Server Error” message
Remove SPLA licensing section under circumstances where RDS licenses will not be required
Include Automatic SSL certificate handling and Automatic SMTP to the provisoning wizard inside CWMS

=== 5.2 Cloud Workspace Tools and Services

When a VDI user logs out of their VM at a time it is set to be powered off, power off that VM
Azure Backup enhancement – when restoring TSD1 servers as a VM, restore as a TS VM instead of an additional TSD VM
Steamlined preparation of Azure VMs for Azure Backup handling
Back end processing speed and security improvements

=== 5.2 REST API

Improved handling of server information, enabling faster Wake-on-Demand server load times

== CWMS 5.2 Release: Thurs., July 11, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday July 11, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Tools and Services

Ongoing behind the scenes security enhancements
Ongoing stability enhancements for auto-generated certificates
Least Privileged methodology improvement – adjustment to use an account with fewer permissions/less affected by generic lockdowns to perform nightly reboots
Improvements for integrated backups for Azure deployments
Improvements for integrated backups for GCP deployments
Bug fix to no longer unecessarily reboot servers to apply resource adjustments when they were already correct
Process enhancement to allow for manual certificate management, if desired

== CWMS 5.2 Release: Thurs., June 20, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday June 20, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Improved handling of Users imported into CWMS via the CRA process
Correct storage displays in the Server section of the Workspace module for a subset of scenarios
Updated year at the bottom of the CWMS web interface

=== 5.2 Cloud Workspace Tools and Services

Enhanced automated certificate automation

=== 5.2 REST API

Display correction – display the correct values previously entered in the Live Scaling feature when opening the Live Scaling feature again
Allow for creation of a default backup schedule for the Power User role (VDI Users).

== CWMS 5.2 Release: Thurs., June 6, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday June 6, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Tools and Services

Improved handling of multiple emails for platform notifications
Bug fix for a subset of scenarios where Workload Scheduling was not turning servers off correctly
Bug fix for a subset of scenarios where restoring servers from Azure Backup didn’t restore the proper storage type vs. a default storage type

=== 5.2 CWA Setup

Continued security enhancements during the CWA Setup Process
Improved automated handling of subnet and gateway settings
Improved behind-the-scenes process of handling user accounts during the registration process
Includes a process to refresh tokens in the event a user remains in the CWA Setup process for more than 1 hour

== CWMS 5.2 Release: Thurs., May 23, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday May 23, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Improved link in the WVD tab in the Workspaces module
Bug fix for a scenario where clicking a link to a Workspace from the Data Centers module wouldn’t take you to that Workspace
Bug fix for a scenario where updating the contact info for a Primary Admin would remove their designation as Primary Admin

== CWMS 5.2 Release: Thurs., May 9, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday May 9, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Tools and Services

Scalability improvements for deployments with several hundred to several thousand VMs

== CWMS 5.2 Release: Thurs., April 25, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday April 25, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Interface improvement – in the event backups are not enabled for a server in Azure or GCP, remove the size column from the Backup section of a server

=== 5.2 Cloud Workspace Tools and Services

Bug fix for a scenario where changing resources for RDP and/or HTML5 gateway servers would not bring them back online after the resource change was complete

=== 5.2 REST API

Improved handling of initial MFA configurations, regardless of scenario

=== 5.2 CWA Setup

Support for existing CWMS accounts, empowering indirect CSPs to provision correctly and simplifying the process for existing Partners
Additional validation for Azure Active Directory Domain Services – display an error if Azure Active Directory Domain Services is selected, but is already in place

== CWMS 5.2 Release: Thurs., April 11, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday April 11, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Bug fix for Provisioning Collections – saving a Provisioning Collection with an app that does not havea a desktop icon will no longer display an error in CWMS
Bug fix – resolve an issue where starting a stopped platform server from CWMS displayed an error because there was no Partner code attached

=== 5.2 Cloud Workspace Tools and Services

Stability enhancement for deleting servers in vCloud deployments – in the event that multiple FMs are found in one vApps, only delete the VM instead of deleting the vApp
Add an option to not install wildcard certificates on infrastructure servers
Improvements for cloning TSD servers in AzureAD
Improvements for Server Resource Report – handling servers with multiple IP addresses
Bug fix for a subset of scenarios when a list of backups for a server didn’t load for review in AzureRM
Bug fix when attempting to clone VMs with a prefix in Azure Classic (all new and recent deployments use AzureRM)
Bug fix for DNS errors not being reported correctly in the Server Resource Report for Server 2008 R2
Bug fix for not sending the Company Resource report in the event that a VM deleted from the hypervisor (but not from AD) and CWMS cannot find Azure backups in the hypervisor r itself (only in AzureRM deployments)

=== 5.2 CWA Setup

Adding a method to validate that the region selected to provision into has Azure Active Directory Domain Services available
Adding additional checks to resolve DNS timeout issues in a subset of scenarios
Remove B2s as a target for CMGR1 deployment, as it was slowing down the deployment process

== CWMS 5.2 Release: Thurs., March 28, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday March 28, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Add Windows Virtual Desktop section to the CWMS interface
Allow a CWMS Admin to not set a company logo under Settings -> Logo
Add requirement for External ID when updating an app in a Custom App Catalog

=== 5.2 Cloud Workspace Tools and Services

Further streamlining and improvements to the Cloud Workspace for Azure (CWA) deployment process
A Premium Storage account is no longer required to create VMs with Premium Storage in Azure RM deployments
Resolve an issue in a subset of scenarios where Application Usage Tracking reports did not capture usage data
Resolve an issue where updating certificates on HTML5 portal servers would result in an error as HTML5 portal server licensing was updated
Bug fix for Password Expiration Notifications not updating passwords when using Azure Active Directory Domain Services
Adjusted location to which Password Expiration Notifications writes log files

=== 5.2 REST API

Bug fix for starting/stopping Platform servers (not Customer servers) in the Data Center module

=== 5.2 CWA Setup

Improvements for FTP role settings during deployment
Improved mechanism to ensure Admins are seeing the latest release every time they access the CWA Setup process
Improved handling of elements that time out during deployment
Bug fix for a scenario where a deployment was incorrectly tagged as using Azure AD

== CWMS 5.2 Minor Release: Thurs., March 14, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday March 14, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Change the name of the “Application Monitoring” feature to “Application Usage Tracking”
Apply a fix where refreshing a search for Scripted Events does not re-use selected start/end dates
Default File Audit to start with the date filter set to one day prior to the current date, streamlining the amount of data returned
Bug fix to Integrated Backups for Azure where restoring backups to a server was not functioning as intended in a subset of scenarios
Resolve an application error prompt when updating a Client that belongs to an App Service

=== 5.2 REST API

Azure safeguard – when adding an Azure AD User, ensure that their email address is not already added to the account.
Bug fix – when adding an application for a Client and creating a Group at the same time, add the Users to the Group as intended
Add a validation step when disabling access to RDSH servers that ensures it is still applied after a server is rebooted
General improvements for CWA workflow automation
Bug fix for a subset of scenarios when adding an App to a Group affected other Users of that Group

=== 5.2 CWA Setup

Add a refresh option for the list of subscriptions during the deployment process
Auto-set deployment flag for degraded, legacy MobileDrive service to False
Additional automation safeguards and checks in Azure

== CWMS 5.2 Minor Release: Thurs., February 28, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday February 28, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Improved clarity and confirmation message for what happens when deselecting the “VDI User” checkbox for Users in the CWMS interface (deletes VDI User’s server) and how to proceed if you do not want to delete the server
Back-end improvements to timestamp handling

=== 5.2 Cloud Workspace Tools and Services

Updated settings for the license server name in Azure Domain Services
Behind-the-scenes improvements to the process by which a User can change their own password after being logged into their Cloud Workspace
Updated native 2FA to reflect CloudJumper imagery
Bug fix for 2FA if a rare setting is enabled

=== 5.2 CWA Setup

Additional Help/Support content in the CWA Setup wizard
Add agreement terms and pricing to the CWA Setup wizard
Improved mechanism for detecting a Subscription’s quota and permissions
Streamline deployments for Azure Active Directory Domain Services based deployments
Behind-the-scenes improvement to the storage account name format
Bug fix for FTP server settings in a subset of scenarios

== CWMS 5.2 Minor Release: Thurs., February 14, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday February 14, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Performance improvement in User management actions
Additional logging enabled to display who requested a change on a Group in the Data Center task history
Resolve an issue in the Standard App Catalog where applications were not displaying in a subset of scenarios
Resolve an issue in App Services with Dynamic Provisioning where an error is displayed if two applications with the same name are
Remove the SDDC creation wizard from the CWMS 5.1 interface
* If you are running a SDDC that is on 5.1 and you wish to provision a new SDDC, please contact support@cloudjumper.com to schedule an upgrade to CWMS 5.2
Correct a spelling error in the API User creation screen of CWMS

=== 5.2 Cloud Workspace Tools and Services

In vCloud based SDDCs, re-login to the hypervisor in the event the connection expires
In vCloud based SDDCs, increase the default timeout when waiting for servers to boot up
Improved limitations on CloudJumper’s administrative access

=== 5.2 REST API

When provisioning a new SDDC via the 5.1 interface of CWMS, the message displayed will be “New data center creation is only supported when using v5.2 of CWMS.”

=== 5.2 CWA Setup

Improved automatic error handling

== CWMS 5.2 Minor Release: Thurs., January 31, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday January 31, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Add the Cloud Workspace client server’s connection info to the Cloud Workspace client’s Overview section
Add an editable field in CWMS Account Settings that allows you to enter your Azure AD Tenant ID
Use the most modern version of Microsoft Standard Storage in new Azure deployments
Improved Azure integration, requiring Integrated Backups in Azure deployments to be retained for at least 1 day
Improved handling in Dynamic Provisioning for App Services deployments
Add the date at which server storage is inventoried to that section of the Servers module
Display that an app is provisioned to a User while the User’s status is still Pending Cloud Workspace
If a User is a VDI User, display the VDI Server on the User page
If a server is for a VDI User, display the User on the Server page
Resolve an issue in certain scenarios where if a User has an open Service Board task associated with their username, remote access to the VM fails from CWMS

=== 5.2 Cloud Workspace Tools and Services

Improved handling of Live Scaling as Users log in throughout the day
Add automation prerequisites for future Wake on Demand improvements
Add automation prerequisites for future Workload Scheduling improvements
Resolve an issue where using Windows 10 for VDI servers was not properly enabling the remote registry service in Azure Active Directory Domain Services deployments
Resolve an issue where using Windows 10 for VDI servers was not properly setting the security group for the local Remote Desktop Users group in Azure Active Directory Domain Services deployments
Modify PCI compliance setting feature to take no action when not enabled instead of enforcing default configuration settings
Resolve a issue in Workload Scheduling so that Users with Wake on Demand enabled that log out can power down servers if they are scheduled to be powered down
Fix a bug when cloning a server in ProfitBricks public cloud
Fix a bug where cloning servers checks server prefixes to that server names aren’t duplicated in VDI User scenarios
Add a check in nightly reports for cached customer codes that are not using a valid provisioning collection
Improved handling of exceptions when both the VM is not in the hypervisor and CWAgent requires an update
Resolve issue resetting passwords via Password Expiration Notification to correctly enforce password history

=== CWA Setup

Implement option to automatically configure SMTP settings
Adding validation options for the location list to checks if the subscription has enough quota and enough permissions to create VMs in the selected Azure region
Added feature to remove unneeded Cloudworkspace and other service accounts with administrative permissions at the end of the provisioning process in Azure
Notify Users that manual DNS certificate uploads have been verified
Resolved an issue where ThinPrint installations don’t install as intended in certain scenarios

== CWMS 5.2 Minor Release: Thurs., January 17, 2019

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday January 17, 2019 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

The Workload Scheduling interface will now display Description as the first column and change the name of Scheduling to Custom Scheduling
Bug fix for displaying backups of platform servers in Azure deployments
Bug fix for scenarios where End User self-administration for App Services use cases where the organization does not have any Cloud Workspace services set up

=== 5.2 Cloud Workspace Tools and Services

Add Support for PCI v3 compliance
Security enhancement: new CWMS deployments will use a local admin vs. a domain admin to run the CWAgent processes.
Support for Windows Server 2019 in AzureRM deployments
* Note: Microsoft does not support Microsoft Office in this version yet
Improved handling of Wake on Demand Users – if their organization is scheduled to power VMs down but a User with Wake on Demand is still actively working, do not power down the organization’s VMs
Stability improvement when cloning VMs – remove roles like Connection Broker from the newly created VM coming from the cloned VM.
Improved process for installing the ThinPrint license server role
Improved AzureRM template handilng – return all templates available for a VM in Azure based on the hardware it runs on, not just templates available in the tenant’s Azure region
Improved automated testing for vSphere deployments
Include a check in nightly email reports to see if ThinPrint license server is installed
Bug fix for Live Scaling in a limited subset of scenarios
Bug fix for cloning servers in certain scenarios in vCloud deployments
Bug fix for VM name prefixes in AzureRM deployments
Bug fix for reporting error when using custom machine sizes in Google Cloud Platform
Bug fix for reporting Users with ThinPrint functionality enabled
Exclued Chinese version of Windows from the list of templates available in AzureRM

=== CWA Setup

Fix a scenario where passwords that meet the minimum number of characters required were not accepted
Change the ID column to Customer Domain during the tenant selection process for CSPs
Update to the signup process that streamlines credit card entry

== CWMS 5.2 Minor Release: Thurs., December 20, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday December 20, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Setup

Added a feature of FTP DNS Registration in the event of a single-server deployment and Automatic SSL is selected during the deployment process
Automated process for populating Azure AD info. (Tenantid, ClientId, Key) into back-end tables
The automated installation process will now install ThinPrint License Server 11 instead of 10

=== 5.2 CWA Setup

Fix an issue where the registration process redirected admins to a sign in page when completed

== CWMS 5.2 Minor Release: Thurs., December 6, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday December 6, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Tools and Service

Support for creating servers with Win10 OS
Improved speeds when loading a VM from the hypervisor
Return correct storage types available when creating servers in Azure
Add logging of daily reports to the back end of the control plane
Avoid a scenario where temp drives could expand automatically in Azure
Lay the foundation for a future change to display server OS when selecting a template for provisioning
Bug fix for not automatically expanding a drive in GCP
Bug fix for deployment automation when using Azure Active Directory Domain Services
If multiple MGR severs are configured, note an error in the nightly report
Bug fix for automated tests for public cloud (Azure, GCP) backups in VMware deployments
Bug fix for determining disk space on a new VM created via HyperV deployments
Bug fix for collecting server data when AD root OU is blank
Stability improvement when cloning servers based off of a mis-configured hypervisor

=== 5.2 REST API

Enable support for machine series in public clougd deployments
Allow the Default Resource Allocation to be Disabled for an SDDC
Added DataCollectedDateUTC to storage details for a server
Add the ability to Compute resource values
Add a new method to get detailed user connection statuses
Display an error in CWMS when deleting a user that also had admin rights
Fixed issue with drive mapping for a data enabled app service not always appearing
Fixed issue updating a client and/or user via CWMS that was imported via CWA
Fixed issue when a new user was created and applications were assigned to the all users group, the new user would not receive the application shortcuts.

== CWMS 5.2 Minor Release: Thurs., November 1, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday November 1, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Bug fix for integrated backups
Bug fix for a specific use case in a CRA deployment

=== 5.2 Cloud Workspace Tools and Services

Enable the ability to return storage types availabe in Azure ARM deployments when creating servers
Support for multi-site Active Directory topology
Fix an issue with TestVDCTools when using Azure Active Directory Domain Servce
Bug fix for nightly email reports when AD root OU is blank

=== 5.2 REST API

Support unlocking Users when Azure Active Directory Domain Services. Note: please be aware that there may be a delay of up to 20 minutes due to replication.

== CWMS 5.2 Minor Release: Thurs., October 18, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday October 18th, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

in the Data Center wizard, enable validation of wildcard certificates
General behind-the-scenes improvements and bug fixes
Add a search function in the applications table
Improved sorting in the applications table
Add details for completing DNS registration in the Data Center provisioning process
Include all Sub Partner Users and groups in API call responses for Dynamic App Services
Fix a bug where migration mode didn’t persist for a tenant in a specific instance
Add Extra Powered On Servers, Shared Users per Servers and Max Shared Users per Server to live scaling details
Add DNS validation to the wildcard certificate testing when provisioning via the new Data Center wizard

=== 5.2 Cloud Workspace Tools and Service

Enable an option to return all VM sizes grouped by VM series
Return all VM sizes available from the hypervisor
Fix to Resource Allocation when calculating App Service Users
Enable option for automatic resource update for CWMGR1
Include wildcard cert status DataCenterResources Report
Enable future DNS enhancements
Bug fix – fix to automatic drive expansions in GCP deployments

=== 5.2 REST API

Performance improvements when listing Clients/Users
Allow support for new Live Scaling features – configuring ExtraPoweredOnServers, SharedUsersPerServer and MaxSharedUsersPerServer
API now supports the ability to validate wildcard certificate domain when creating new Platform deployments
New API method available to get User activity data for all Partner Clients

Known issue: When using a the “Active Users” or “User Count” dynamic allocation method for resource pool sizing inside an Azure ARM deployment, the “Computed Resource Per Server” summary incorrectly displays the Machine Size as Basic A series type instead of the correct Standard D series type.

== CWMS 5.2 Minor Release: Thurs., September 27, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday September 27th, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Simplify the display of provisioning collection VMs in cache
Fix a display quirk when managing App Services

=== 5.2 Cloud Workspace Tools and Services

Bug fix for an obscure use case for End User MFA
Update API to interface with the latest in Azure RM
Update Testing for Azure RM to use the latest API
Replace Power User terminology with VDI User
Update email report to include additional CPU and RAM for a server
Update the address reports come from – instead of dcnotifications@independenceit.com messages will come from dcnotfications@cloudjumper.com
Allow definition of Users per server and additional VMs to remain on via Live Scaling
Performance improvements when starting a stopped SDDC/deployment
Security enhancement – disallow Partners with multiple SDDCs/deployments from connecting from one to another
Stability improvement – in the event automation cannot return User count, do not make any changes to resource count
Minor cosmetic enhancements

== CWMS 5.2 Minor Release: Thurs., September 6, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday September 6th, 2018 at 10pm – 11pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Added the ability to search for Sub Partners in the Custom App Catalog
Fixed a bug where refreshing the screen in the Data Centers module causes an error prompt
Removing the restriction on max folder name size and making it easier to browse folders
Ensure that resource counts on VMs are never lower than the minimum specified CPU and RAM values
Rephrase Power User terminology to VDI User
Fixed an error where a generic error was displayed despite the back-end process completing successfully
Improved server name display in Data Center creation wizard
Fix account expiration not displaying saved expiration date in CWMS

=== 5.2 Cloud Workspace Tools and Services

Fixed a bug with MFA where Users who selected Email sometimes didn’t receive a code
Allow additional CPU and RAM to be entered for User Count resource allocation type
Fix a bug where the automation engine didn’t power all machine types on
Fixed a timing issue that sometimes would cause cloning servers to err out
Automate the previously manual installation of a wildcard certificate on FTP server
Added a process to purge old certificates after updating wildcard certificates
Resolve an issue where when using Data Enabled Application Services, the X: drive would not always map for an end user.

== CWMS 5.2 General Availability Release:  Thurs., August 10, 2018

Components:  5.2 Cloud Workspace Management Suite
When:  Thursday August 10th, 2018 at 10pm Eastern
Impact:  Access to Cloud Workspace desktops and application services for End Users will remain uninterrupted. Access to Cloud Workspace Management Suite will remain available.

=== 5.2 Cloud Workspace Management Suite

Release web interface components to enable the features found in the overview above

=== 5.2 Cloud Workspace Tools and Services

Release back-end tools to enable the features found in the overview above

=== 5.2 REST API

 Release API to production to enable the features found in the overview above
