
////

Used in: sub.Management.Scripted_Events.scripted_events.adoc

Other GitHub Repos:
VDMS Repo:
remotesub.Management.Scripted_Events.scripted_events.adoc

////

== Overview
Scripted Events provides the advanced administrator with a mechanism to create custom automation for system maintenance, user alerts, group policy management, or other events. Scripts can be designated to run as an executable process and accept arguments, or can be used as arguments for a different executable program. This functionality allows for scripts to be combined and nested to support complex customization and integration needs.

A detailed example of scripted events in action is found in the link:Management.Applications.application_entitlement_workflow.html[Application Entitlement Guide].

Additionally, Scripted Events allows for the creation of automation that does not require a script to process, rather the automation flow is launched by a system trigger and executes an existing program or system utility with optional arguments.

=== Script repository
This section displays all scripts available. Scripts are executed by activities, covered in the next section.

Clicking on the Add button allows for the creation of a new Script.

Clicking Name of a script opens a dialog box for editing the script.

=== Activities

Activities are the way to execute one or more scripts. Activities can be triggered on many system actions. More on automating app installs is found link:Management.Applications.application_entitlement_workflow.html[here].

* Application Install
** This is triggered when the VDS Admin clicks "+ Add..." from the _Workspace > Applications_ page.
** This selection allows you to select an application from the Application Library and to pre-define the shortcut of the application.
** Detailed instructions for this trigger are highlighted in the link:scriptlibrary.AdobeReader.html#install-script[_Install Adobe Reader DC_ script documentation].
* Application Uninstall
** This is triggered when the VDS Admin clicks "Actions > Uninstall" from the _Workspace > Applications_ page.
** This selection allows you to select an application from the Application Library and to pre-define the shortcut of the application.
** Detailed instructions for this trigger are highlighted in the link:scriptlibrary.AdobeReader.html##uninstall-script[_Uninstall Adobe Reader DC_ script documentation].
* Create Cache
** This is triggered anytime a new VM is built by VDS for a provisioning collection cache
* Create Client
** This is triggered anytime a new Client organization is added to VDS
* Create Server
** This is triggered anytime a new VM is built by VDS
* Create User
** This is triggered anytime a new user is added via VDS
* Delete User
** This is triggered anytime a new user is deleted via VDS
* Manual
** This is triggered by a VDS admin manually from within the "Scripted Events > Activity" page
* Manual Application Update
**
* Scheduled
** This is triggered when the defined date/time is reached
* Start Server
** This is triggered on a VM each time it boots up

Clicking on the _Name_ opens a dialog box where the activity can be edited.
