////

Used in:
sub.Management.Applications.application_entitlement_workflow.adoc
sub.Management.User_administration.manage_application_access.adoc

Other GitHub Repos:
VDMS Repo:
remotesub.Management.Applications.application_entitlement_workflow.adoc
remotesub.Management.User_Administration.manage_application_access.adoc

////

== Overview
VDS has a robust application automation and entitlement functionality built-in. This functionality allows users to have access to different applications while connecting to the same session host(s). This is accomplished by some custom GPOs hiding shortcuts along with automation selectively placing shortcuts on the users’ desktops.

NOTE: This workflow only applies to RDS deployments.  For WVD application entitlement documentation, please see link:Management.Applications.wvd_application_entitlement_workflow.html[Application Entitlement Workflow for WVD]

Applications can be assigned to users directly or via Security groups managed in VDS.

.At a high level, the application provisioning process follows these steps.
. Add App(s) to App Catalog
. Add App(s) to the workspace
. Install the Application on all Session Hosts
. Select the Shortcut path
. Assign apps to users and/or groups

NOTE: Steps 3 & 4 can be fully automated with Scripted Events as illustrated below

.Video Walkthrough
video::19NpO8v15BE[youtube]

== Add applications to the App Catalog
VDS Application Entitlement starts with the App Catalog, this is a listing of all the applications available for deployment to end user environments.

.To add applications to the catalog, follow these steps
. Log in to VDS at https://manage.cloudworkspace.com using your primary admin credentials.
. In the upper right, click the arrow icon next to your User Name and select Settings.
. Click the App Catalog tab.
. Click the Add App option in the Application Catalog title bar.
. To add a group of applications, choose the Import Apps option.
.. A dialog will appear that provides an Excel template to download that creates the correct format for the application list.
.. For this evaluation NetApp VDS has created a sample application list for import it can be found here.
.. Click on the Upload area and choose the application template file, click the Import button.
. To add individual applications, choose the Add App button and a dialog box will appear.
.. Enter the name of the application.
.. External ID can be used to enter an internal tracking identifier such as a product SKU or billing tracking code (optional).
.. Check the Subscription box if you want to report on the applications as a Subscription product (optional).
.. If the product does not install by version (for example Chrome) check the Version Not Required checkbox. This allows “continuous update” products to be installed without tracking their versions.
.. Conversely, if a product supports multiple named versions (ex: Quickbooks) you need to check this box so that you can install multiple versions and have VDS specific each available version in the list of applications that can be entitled for and end user.
.. Check “No User Desktop Icon” if you don’t want VDS to provision a desktop icon for this product. This is used for “backend” products like SQL Server since end users don’t have an application to access.
.. “App Must be Associated” enforces the need for an associated app to be installed. For example, a client server application may require SQL Server or mySQL to be installed as well.
.. Checking the License Required box indicates that VDS should request a license file to be uploaded for an installation of this application before it sets the application status to active. This step is performed on the Application detail page of VDS.
.. Visible to All – application entitlement can be limited to specific subpartners in a multi-channel hierarchy. For evaluation purposes, click the Check Box so that all users can see it in their available application list.

== Add the application to the Workspace
To start the deployment process you'll add the app to the workspace.

.To do this, follow these steps
. Click Workspaces
. Scroll down to Apps
. Click Add
. Check box the application(s), enter required information, click Add Application, click Add Apps.

== Manually install the application
Once the application has been added to the Workspace you'll need to get that application installed on all session hosts. This can be done manually and/or it can be automated.

.To manually install applications on session hosts, follow these steps
. Navigate to Service Board.
. Click on the Service Board Task.
. Click on the Server Name(s) to connect as a local admin.
. Install the app(s), confirm the shortcut to this app is found in the Start Menu path.
.. For Server 2016 and Windows 10: C:\ProgramData\Microsoft\Windows\Start Menu\Programs.
. Go back to the Service Board Task, click Browse and choose either the shortcut or a folder containing shortcuts.
. Whichever you select is what will be displayed on the end user desktop when assigned the app.
. Folders are great when an app is actually multiple applications. e.g “Microsoft Office” is easier to deploy as a folder with each app as a shortcut inside the folder.
. Click Complete Installation.
. If required, open the created Icon Add Service Board Task and confirm the icon has been added.



== Assign applications to users

Application entitlement is handled by VDS and application can be assigned to users in three ways

.Assign Applications to Users
. Navigate to the User Detail page.
. Navigate to the Applications section.
. Check the box next to all applications required by this user.

.Assign users to an application
. Navigate to the Applications section on the Workspace Detail page.
. Click on the name of the application.
. Check the box next to the users the application.

.Assign applications and users to user groups
. Navigate to the Users and Groups Detail.
. Add a new group or edit an existing group.
. Assign user(s) and application(s) to the group.
