
////

Used in: sub.Management.User_Administration.multi-factor_authentication.adoc

////

== Overview
NetApp Virtual Desktop Service (VDS) includes an SMS/Email based MFA service at no additional charge.  This service is independent of any other services (e.g. Azure Conditional Access) and can be used to secure administrator logins to VDS and user logins to virtual desktops.

== MFA basics
* VDS MFA can be assigned to admin users, individual end users or applied to all end users
* VDS MFA can send SMS or Email notifications
* VDS MFA has a self-service initial setup and reset function

== Guide scope
This guide walks you thru the setup of MFA along with an illustration of the end user experience

.This guide covers the following subjects:
. <<Enabling MFA for Individual Users,Enabling MFA for Individual Users>>
. <<Requiring MFA for All Users,Requiring MFA for All Users>>
. <<Enabling MFA for Individual Administrators ,Enabling MFA for Individual Administrators>>
. <<End User Initial Setup,End User Initial Setup>>


== Enabling MFA for individual users
MFA can be enabled for individual users on the user detail page by clicking _Multi-factor Auth Enabled_

Workspaces > Workspace Name > Users & Groups > User Name > Multi-factor Auth Enabled > Update

MFA can also be assigned to all users, if this setting is in place, the checkbox will be checked and _(via Client Settings)_ will be appended to the checkbox label.

== Requiring MFA for all users
MFA can be enabled and enforced across all users on the workspace detail page by clicking _MFA for All Users Enabled_

Workspaces > Workspace Name > MFA for All Users Enabled >Update

== Enabling MFA for individual administrators
MFA is also available for administrator accounts accessing the VDS portal. This can be enabled per administrator on the admin detail page.
Admins > Admin Name > Multi-Factor Auth Required > Update

== Initial setup
On the first login after enabling MFA, the user or admin will be prompted to enter an email address or mobile phone number. They'll receive a confirmation code to enter and confirm successful enrollment.
